version: '3.9'

volumes: # named volumes can be managed easier using docker-compose
  ant-media-volume:
    external: false # docker expected to already exist if true


services:
  # Ant Media Service  ####################
  ant-media-service:
    image: "nibrev/ant-media-server:ams-v2.5.3"
    container_name: "ant-media-container"
    restart: always
    # restart after enable ssl and use 5443 port to access <https://yourdomain:5443>
    command:
      - /bin/bash
      - -c
      - |
        ./usr/local/antmedia/enable_ssl.sh <yourdomain>
    volumes:
      - ant-media-volume:/usr/local/antmedia/ # persist data even if container shuts down
    network_mode: host # Because of the nat issue you have to use host mode
    # above means that Ant Media Server uses the host network. It is required because
    # there is a wide range of UDP and TCP ports are being used for WebRTC streaming.
    #This also means that you can only use one pod of Ant Media Server in a host instance.