version: '3.9'

volumes: # named volumes can be managed easier using docker-compose
  ant-media-volume:
    external: false # docker expected to already exist if true

networks: # defining user defined network adds DNS by name of the service resolver for your services
  bridge-network:
    driver: bridge
  host-network: # Directly connected to host network and no need to expose ports. Useful for VPN: Wire guard or Kamailio
    driver: host # driver means network type
    external: false # docker expected to already exist if true


services:
  # Ant Media Service  ####################
  ant-media-service:
    image: "nibrev/ant-media-server:ams-v2.5.3"
    container_name: "ant-media-container"
    restart: always
    volumes:
      - ant-media-volume:/usr/local/antmedia/ # persist data even if container shuts down
    network_mode: host # Just work in linux. https://docs.docker.com/network/network-tutorial-host/#prerequisites The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.


